Sligth clean-up

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -16,13 +16,41 @@ Vagrant.configure(2) do |config|
    end
   config.vm.provision "shell", inline: <<-SHELL
 
+function download_requirements () {
+wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm http://downloads.haskell.org/~ghc/7.10.2/ghc-7.10.2-x86_64-unknown-linux-centos66.tar.bz2 https://www.haskell.org/cabal/release/cabal-install-1.22.6.0/cabal-install-1.22.6.0.tar.gz https://raw.githubusercontent.com/elm-lang/elm-platform/master/installers/BuildFromSource.hs
+if [ $? -eq 0 ];then
+cat << EOC
+ ______                    _
+(_____ \                  (_)                               _
+ _____) )_____  ____ _   _ _  ____ _____ ____  _____ ____ _| |_  ___
+|  __  /| ___ |/ _  | | | | |/ ___) ___ |    \| ___ |  _ (_   _)/___)
+| |  \ \| ____| |_| | |_| | | |   | ____| | | | ____| | | || |_|___ |
+|_|   |_|_____)\__  |____/|_|_|   |_____)_|_|_|_____)_| |_| \__|___/
+                  |_|
+     _                   _                 _           _
+    | |                 | |               | |         | |
+  __| | ___  _ _ _ ____ | | ___  _____  __| |_____  __| |
+ / _  |/ _ \| | | |  _ \| |/ _ \(____ |/ _  | ___ |/ _  |
+( (_| | |_| | | | | | | | | |_| / ___ ( (_| | ____( (_| |
+ \____|\___/ \___/|_| |_|\_)___/\_____|\____|_____)\____|
+EOC
+else
+echo "Could not download files, please verify you have internet conection"
+exit 1
+fi
+}
+
 function install_packages () {
-wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
 rpm -ivh epel-release-6-8.noarch.rpm
+echo "RPM epel released $?"
 yum update
+echo "Yum update $?"
 yum -y install emacs ncurses-devel ncurses zlib-devel git nodejs gcc npm glibc gmp-devel
+echo "Yum install $?"
 sudo service iptables stop
+echo "stop iptables $?"
 chkconfig iptables off
+echo "disable iptables $?"
 cat << EOC
  ______            _
 (_____ \          | |
